# Workflow for producing a set of tests and storing them in a ZIP file
#
name: Create a set of test files

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Build test fixtures
        run: python generate_test.py --output tests
      - name: Share artifact inside workflow
        uses: actions/upload-artifact@v2
        with:
          name: plugin-build
          path: ./tests
            
  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Download previously shared build
      - name: Get artifact
        uses: actions/download-artifact@v1
        with:
          name: plugin-build
      # Zip the build using external action
      - name: Zip build
        uses: thedoctor0/zip-release@master
        with:
          filename: text-fixtures.zip
          path: plugin-build
      # Upload as an artifact of the current workflow
      - name: Upload build zip artifact
        uses: actions/upload-artifact@v1
        with:
          name: majority-judgment.zip
          path: majority-judgment.zip
      # Make official GitHub release which will trigger
      # sending the mail with link for access
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: test-fixtures.zip
          token: ${{ secrets.GITHUB_TOKEN }}
